spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Order?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: http://localhost:29092
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8085

