spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Payment?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: http://localhost:29092

server:
  port: 8086

